name: Update README with Language Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск ежедневно в полночь UTC
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Fetch Language Statistics
        env:
          STATS_TOKEN: ${{ secrets.STATS_TOKEN }}
        run: python fetch_languages.py
        
      - name: Update README
        run: |
          LANG_STATS=$(cat LANGUAGES.md)
          awk -v lang_stats="$LANG_STATS" '/<!--languages-start-->/{print;print lang_stats;next}/<!--languages-end-->/{flag=0}flag;/<!--languages-start-->/{flag=1}' README.md > temp_README.md && mv temp_README.md README.md

          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md LANGUAGES.md
          git diff --staged --quiet || git commit -m "Update language statistics in README"
          git diff --staged --quiet || git push

